### ISSUE TITLE
IE & Chrome discrepancy 

### ISSUE THREAD

**Issue by domgaulton** [hugozap/react-svgmt#15]
Using SvgLoader and SvgProxy v 1.1.8 `"react-svgmt": "^1.1.8",` 

When there are multiple matches to the selector the onElementSelected returns multiple nodes. On chrome these render once but multiple times where as on IE the nodes are returned in an array. 

Why is there a difference between IE and Chrome here?

**Comment by garygreenleaf** [comment]
Looking at the code, it appears that there is a fallback in place for IE11 when setting the SVG content because it doesn't support innerHTML prop in SVGElements. However within this code the contents of the existing SVG are not removed before new child elements are appended, causing the contents of the two svgs to be merged rather than updated. PR to fix here #20
