### ISSUE TITLE
SVG path filling seems not effective

### ISSUE THREAD

**Issue by guivinson** [hugozap/react-svgmt#23]
svg path seems resistant to any change on it's style

`<SvgProxy
          selector="#pointsProgressionPath"
          fill="orange"
          stroke="#FF0000"
          stroke-width="5"
        />`

[Demo](https://codesandbox.io/s/react-svgmt-nth-child-wgve5?file=/src/index.js)

**Comment by hugozap** [comment]
The issue here is that the SVG you are using has style attributes which take precedence over the attributes that svgmt sets. If you remove the style attributes that you intend to change it will work.
https://codesandbox.io/s/react-svgmt-nth-child-7bmou?file=/src/index.js

(Had to rename the svg to avoid the cache in my browser after adjusting the SVG)
